name: Build and publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Linux package
        run: ./gradlew packageDeb

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: build/compose/binaries/main/deb/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Windows package
        run: .\gradlew.bat packageExe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: build/compose/binaries/main/exe/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build macOS package
        run: ./gradlew packageDmg

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-package
          path: build/compose/binaries/main/dmg/
