name: Build and publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Linux deb
        run: ./gradlew packageDeb

      - name: Build Linux jar
        run: ./gradlew packageUberJarForCurrentOS

      - name: Upload Linux deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: app/build/compose/binaries/main/deb/

      - name: Upload Linux jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-jar
          path: app/build/compose/jars/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build Windows exe
        run: .\gradlew.bat packageExe

      - name: Upload Windows exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: app/build/compose/binaries/main/exe/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build macOS package
        run: ./gradlew packageDmg

      - name: Build macOS jar
        run: ./gradlew packageUberJarForCurrentOS

      - name: Upload macOS dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: app/build/compose/binaries/main/dmg/

      - name: Upload macOS jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-jar
          path: app/build/compose/jars/